workflows:
  my-workflow:
    name: Build App
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      flutter: 3.27.4
      vars:
        BASE_URL: "https://your-api.com"
        FIREBASE_AUTH_DOMAIN: $FIREBASE_AUTH_DOMAIN
        ...
    scripts:
      - name: Get Flutter Dependencies
        script: flutter pub get

      - name: Decode google-services.json
        script: |
          echo $Google-services.json | base64 --decode > android/app/google-services.json

      - name: Build Android APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - ahmedali205001@gmail.com
