workflows:
  ios-build:
    name: Build iOS App
    environment:
      vars:
        FLUTTER_ROOT: /opt/flutter
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Build iOS
        script: flutter build ios --release --no-codesign
