workflows:
  ios:
    name: iOS Workflow
    platform: ios
    trigger:
      events:
        - push
    scripts:
      - name: Install CocoaPods
        script: |
          gem install cocoapods -v 1.11.2 # تأكد من استخدام النسخة الصحيحة
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
