# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end
